DROP TABLE IF EXISTS project CASCADE;
DROP TABLE IF EXISTS employee CASCADE;

create table employee (
	id integer generated by default as identity,
	age integer not null check (age<=36 AND age>=0),
	role varchar(255) not null,
	level varchar(255) not null,
	name varchar(255) not null,
	fk_pid integer,
	primary key (id)
);
create table project (
   pid integer generated by default as identity,
   p_name varchar (125) not null,
   primary key (p_id)
);


alter table employee add constraint FKdtss7ab4sx4oagfqyacono43a foreign key (fk_pid) references project on delete cascade;