DROP TABLE employee IF EXISTS;

CREATE TABLE employee (
	id integer generated by default as identity,
	age integer not null check (age<=36 AND age>=0),
	role varchar(255) not null,
	level varchar(255) not null,
	name varchar(255) not null,
	primary key (id)
);

ALTER TABLE duck 
ADD CONSTRAINT UK_8qrhl5wlohdjoko9nrorkdjkp UNIQUE (name);